
# Run official build every day at midnight, if code has changed since the last run,
# or every month if the code has not changed. The localization process requires at least every other month
schedules:
- cron: "0 0 * * *"
  displayName: Daily Official Build
  branches:
    include:
    - main
- cron: "0 8 22-28 * 0" # Fourth Sunday of each month at 8:00 UTC
  displayName: "Monthly build check"
  branches:
    include: 
      - main
  always: true # Run even if there have been no source code changes since the last successful scheduled run
  batch: false # Do not run the pipeline if the previously scheduled run is in-progress

trigger:
  batch: true
  branches:
    include:
    - main

variables:
- template: /eng/common/templates-official/variables/pool-providers.yml@self
- name: TeamName
  value: Roslyn

resources:
  repositories:
  - repository: MicroBuildTemplate
    type: git
    name: 1ESPipelineTemplates/MicroBuildTemplate
    ref: refs/tags/release

extends:
  template: azure-pipelines/MicroBuild.1ES.Official.yml@MicroBuildTemplate
  parameters:
    sdl:
      sourceAnalysisPool:
        name: $(DncEngInternalBuildPool)
        image: 1es-windows-2022
        os: windows
    pool:
      name: AzurePipelines-EO
      image: AzurePipelinesWindows2022compliantGPT
      os: windows
    customBuildTags:
    - ES365AIMigrationTooling
    stages:
    - stage: build
      displayName: Build
      jobs:
      - ${{ if and(notin(variables['Build.Reason'], 'PullRequest'), eq(variables['Build.SourceBranch'], 'refs/heads/main')) }}:
        - template: /eng/common/templates-official/job/onelocbuild.yml@self
          parameters:
            LclSource: lclFilesfromPackage
            LclPackageId: 'LCL-JUNO-PROD-SYMREADER'
            MirrorRepo: symreader-converter

      - template: /eng/common/templates-official/jobs/jobs.yml@self
        parameters:
          enableMicrobuild: true
          enablePublishBuildArtifacts: true
          enablePublishTestResults: true
          enablePublishBuildAssets: true
          enablePublishUsingPipelines: true
          enableTelemetry: true
          enableSourceBuild: false
          helixRepo: dotnet/symreader
          jobs:
          - job: Windows
            pool:
              ${{ if or(eq(variables['System.TeamProject'], 'public'), in(variables['Build.Reason'], 'PullRequest')) }}:
                vmImage: 'windows-latest'
              ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
                name: $(DncEngInternalBuildPool)
                demands: ImageOverride -equals 1es-windows-2022
            variables:
            # Only enable publishing in official builds
            - ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
            # Publish-Build-Assets provides: MaestroAccessToken, BotAccount-dotnet-maestro-bot-PAT
              - group: Publish-Build-Assets
              - name: _OfficialBuildArgs
                value: /p:DotNetSignType=$(_SignType) 
                  /p:TeamName=$(TeamName)
                  /p:DotNetPublishUsingPipelines=true
                  /p:DotNetArtifactsCategory=true
                  /p:OfficialBuildId=$(BUILD.BUILDNUMBER)
            # else
            - ${{ if or(eq(variables['System.TeamProject'], 'public'), in(variables['Build.Reason'], 'PullRequest')) }}:
              - name: _OfficialBuildArgs
                value: ''
            strategy:
              matrix:
                ${{ if or(eq(variables['System.TeamProject'], 'public'), in(variables['Build.Reason'], 'PullRequest')) }}:
                  Debug:
                    _BuildConfig: Debug
                    _SignType: test
                    _BuildArgs: ''
                Release:
                  _BuildConfig: Release
                  # PRs or external builds are not signed.
                  ${{ if or(eq(variables['System.TeamProject'], 'public'), in(variables['Build.Reason'], 'PullRequest')) }}:
                    _SignType: test
                    _BuildArgs: ''
                  ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
                    _SignType: real
                    _BuildArgs: $(_OfficialBuildArgs)
            steps:
            - checkout: self
              clean: true
            - script: eng\common\cibuild.cmd -configuration $(_BuildConfig) -prepareMachine $(_BuildArgs)
              displayName: Build and Test
            - ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
              - task: 1ES.PublishNuget@1
                displayName: Publish CoreXT Packages
                inputs:
                  command: push
                  packagesToPush: '$(Build.SourcesDirectory)\artifacts\packages\$(_BuildConfig)\Shipping\*.nupkg'
                  packageParentPath: $(Build.SourcesDirectory)\artifacts\packages\$(_BuildConfig)\Shipping\
                  allowPackageConflicts: true
                  nuGetFeedType: external
                  publishFeedCredentials: 'DevDiv - VS package feed'
                condition: succeeded()
          - ${{ if or(eq(variables['System.TeamProject'], 'public'), in(variables['Build.Reason'], 'PullRequest')) }}:
            - job: MacOS
              displayName: 'MacOS'
              pool:
                vmImage: 'macOS-latest'
              strategy:
                matrix:
                  Debug:
                    _BuildConfig: Debug
                    _SignType: none
                  Release:
                    _BuildConfig: Release
                    _SignType: none
              steps:
              - checkout: self
                clean: true
              - script: eng/common/cibuild.sh --configuration $(_BuildConfig) --prepareMachine
                displayName: Build and Test
            - job: Linux
              displayName: 'Linux'
              pool:
                vmImage: 'ubuntu-latest'
              strategy:
                matrix:
                  Debug:
                    _BuildConfig: Debug
                    _SignType: none
                  Release:
                    _BuildConfig: Release
                    _SignType: none
              steps:
              - checkout: self
                clean: true
              - script: eng/common/cibuild.sh --configuration $(_BuildConfig) --prepareMachine
                displayName: Build and Test
    - ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
      - template: /eng/common/templates-official/post-build/post-build.yml@self
        parameters:
          publishingInfraVersion: 3
          enableSymbolValidation: false
