# Branches that trigger builds on PR
pr:
  branches:
    include:
    - main
    - release/*
  paths:
    exclude:
    - README.md
    - docs/*

variables:
  - template: /eng/common/templates/variables/pool-providers.yml
  - name: _PublishUsingPipelines
    value: true

stages:
- stage: build
  displayName: Build
  jobs:
  - template: /eng/common/templates/jobs/jobs.yml
    parameters:
      enableMicrobuild: true
      enablePublishBuildArtifacts: true
      enablePublishTestResults: true
      enablePublishBuildAssets: true
      enablePublishUsingPipelines: $(_PublishUsingPipelines)
      enableTelemetry: true
      helixRepo: dotnet/symreader
      jobs:
      - job: Windows
        pool:
          vmImage: 'windows-latest'
        strategy:
          matrix:
            Debug:
              _BuildConfig: Debug
              _SignType: test
              _DotNetPublishToBlobFeed: false
              _BuildArgs: ''
            Release:
              # PRs or external builds are not signed.
              _BuildConfig: Release
              _SignType: test
              _DotNetPublishToBlobFeed: false
              _BuildArgs: ''
        steps:
        - checkout: self
          clean: true
                      
        - script: eng\common\cibuild.cmd -configuration $(_BuildConfig) -prepareMachine $(_BuildArgs)
          displayName: Build and Test
