//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.DiaSymReader.Tools {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ConverterResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConverterResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.DiaSymReader.Converter.ConverterResources", typeof(ConverterResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both ForwardMethodInfo custom debug information and imports are specified.
        /// </summary>
        internal static string BothForwardMethodInfoAndImportsSpecified {
            get {
                return ResourceManager.GetString("BothForwardMethodInfoAndImportsSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDB contains both Source Link and srcsrv data.
        /// </summary>
        internal static string BothSourceLinkDataAndSourceServerData {
            get {
                return ResourceManager.GetString("BothSourceLinkDataAndSourceServerData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both StateMachineTypeName custom debug information and imports are specified.
        /// </summary>
        internal static string BothStateMachineTypeNameAndImportsSpecified {
            get {
                return ResourceManager.GetString("BothStateMachineTypeNameAndImportsSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to token 0x{0:X8}.
        /// </summary>
        internal static string DiagnosticLocation {
            get {
                return ResourceManager.GetString("DiagnosticLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple DynamicLocals custom debug information records specified for the same local variable slot: {0}.
        /// </summary>
        internal static string DuplicateDynamicLocals {
            get {
                return ResourceManager.GetString("DuplicateDynamicLocals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple TupleElementNames custom debug information records specified for the same local constant: &apos;{0}&apos; [{1}, {2}).
        /// </summary>
        internal static string DuplicateTupleElementNamesForConstant {
            get {
                return ResourceManager.GetString("DuplicateTupleElementNamesForConstant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple TupleElementNames custom debug information records specified for the same local variable slot: {0}.
        /// </summary>
        internal static string DuplicateTupleElementNamesForSlot {
            get {
                return ResourceManager.GetString("DuplicateTupleElementNamesForSlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ForwardMethodInfo custom debug information forwards to a method with no scope: 0x{0:X8}.
        /// </summary>
        internal static string ForwardedToMethodWithNoScope {
            get {
                return ResourceManager.GetString("ForwardedToMethodWithNoScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ForwardMethodInfo custom debug information forwards to non-existent method: 0x{0:X8}.
        /// </summary>
        internal static string ForwardedToUndefinedMethod {
            get {
                return ResourceManager.GetString("ForwardedToUndefinedMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import string is too long. Ignoring the import: &apos;{0}&apos;.
        /// </summary>
        internal static string ImportStringTooLong {
            get {
                return ResourceManager.GetString("ImportStringTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The format of import string is invalid: &apos;{0}&apos;.
        /// </summary>
        internal static string InvalidEntryPointToken {
            get {
                return ResourceManager.GetString("InvalidEntryPointToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The format of import string is invalid: &apos;{0}&apos;.
        /// </summary>
        internal static string InvalidImportStringFormat {
            get {
                return ResourceManager.GetString("InvalidImportStringFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid local constant data.
        /// </summary>
        internal static string InvalidLocalConstantData {
            get {
                return ResourceManager.GetString("InvalidLocalConstantData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid local constant signature: &apos;{0}&apos;.
        /// </summary>
        internal static string InvalidLocalConstantSignature {
            get {
                return ResourceManager.GetString("InvalidLocalConstantSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid local scope.
        /// </summary>
        internal static string InvalidLocalScope {
            get {
                return ResourceManager.GetString("InvalidLocalScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid local variable data.
        /// </summary>
        internal static string InvalidLocalVariableData {
            get {
                return ResourceManager.GetString("InvalidLocalVariableData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid PDB format: {0}.
        /// </summary>
        internal static string InvalidPdbFormat {
            get {
                return ResourceManager.GetString("InvalidPdbFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid scope IL offset range: [{0}, {1}).
        /// </summary>
        internal static string InvalidScopeILOffsetRange {
            get {
                return ResourceManager.GetString("InvalidScopeILOffsetRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid sequence point document.
        /// </summary>
        internal static string InvalidSequencePointDocument {
            get {
                return ResourceManager.GetString("InvalidSequencePointDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Source Link data.
        /// </summary>
        internal static string InvalidSourceLinkData {
            get {
                return ResourceManager.GetString("InvalidSourceLinkData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid srcsrv data.
        /// </summary>
        internal static string InvalidSourceServerData {
            get {
                return ResourceManager.GetString("InvalidSourceServerData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid type name specified in StateMachineTypeName custom debug information: {0}.
        /// </summary>
        internal static string InvalidStateMachineTypeName {
            get {
                return ResourceManager.GetString("InvalidStateMachineTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user entry point in the source PDB.
        /// </summary>
        internal static string InvalidUserEntryPointInSourcePdb {
            get {
                return ResourceManager.GetString("InvalidUserEntryPointInSourcePdb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local constant name too long.
        /// </summary>
        internal static string LocalConstantNameTooLong {
            get {
                return ResourceManager.GetString("LocalConstantNameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local scope ranges nesting is invalid.
        /// </summary>
        internal static string LocalScopeRangesNestingIsInvalid {
            get {
                return ResourceManager.GetString("LocalScopeRangesNestingIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local constant name too long.
        /// </summary>
        internal static string LocalVariableNameTooLong {
            get {
                return ResourceManager.GetString("LocalVariableNameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata not available.
        /// </summary>
        internal static string MetadataNotAvailable {
            get {
                return ResourceManager.GetString("MetadataNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method associated with local scope has no body.
        /// </summary>
        internal static string MethodAssociatedWithLocalScopeHasNoBody {
            get {
                return ResourceManager.GetString("MethodAssociatedWithLocalScopeHasNoBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method containing local variables has no local signature.
        /// </summary>
        internal static string MethodContainingLocalVariablesHasNoLocalSignature {
            get {
                return ResourceManager.GetString("MethodContainingLocalVariablesHasNoLocalSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No supported URIs found in Source Link.
        /// </summary>
        internal static string NoSupportedUrisFoundInSourceLink {
            get {
                return ResourceManager.GetString("NoSupportedUrisFoundInSourceLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The PDB doesn&apos;t match debug directory record in the PE file.
        /// </summary>
        internal static string PdbNotMatchingDebugDirectory {
            get {
                return ResourceManager.GetString("PdbNotMatchingDebugDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified PE was built with Portable PDB.
        /// </summary>
        internal static string SpecifiedPEBuiltWithPortablePdb {
            get {
                return ResourceManager.GetString("SpecifiedPEBuiltWithPortablePdb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified PE file doesn&apos;t have any PDB associated with it.
        /// </summary>
        internal static string SpecifiedPEFileHasNoAssociatedPdb {
            get {
                return ResourceManager.GetString("SpecifiedPEFileHasNoAssociatedPdb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream must be readable.
        /// </summary>
        internal static string StreamMustBeReadable {
            get {
                return ResourceManager.GetString("StreamMustBeReadable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream must be seakable.
        /// </summary>
        internal static string StreamMustBeSeakable {
            get {
                return ResourceManager.GetString("StreamMustBeSeakable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream must be writable.
        /// </summary>
        internal static string StreamMustBeWritable {
            get {
                return ResourceManager.GetString("StreamMustBeWritable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An extern alias was not defined for assembly reference {0:X8}.
        /// </summary>
        internal static string UndefinedAssemblyReferenceAlias {
            get {
                return ResourceManager.GetString("UndefinedAssemblyReferenceAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown import definition kind: {0}.
        /// </summary>
        internal static string UnknownImportDefinitionKind {
            get {
                return ResourceManager.GetString("UnknownImportDefinitionKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document name doesn&apos;t match any pattern in Source Link: &apos;{0}&apos;.
        /// </summary>
        internal static string UnmappedDocumentName {
            get {
                return ResourceManager.GetString("UnmappedDocumentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type of import is not supported (type token {0:X8}).
        /// </summary>
        internal static string UnsupportedImportType {
            get {
                return ResourceManager.GetString("UnsupportedImportType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The scheme of URI specified in Source Link is not http/https: &apos;{0}&apos;.
        /// </summary>
        internal static string UriSchemeIsNotHttp {
            get {
                return ResourceManager.GetString("UriSchemeIsNotHttp", resourceCulture);
            }
        }
    }
}
